/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  'custom': [
    {
      type: 'category',
      label: '项目类型',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        '我是需求方/项目类型/整包开发',
        '我是需求方/项目类型/云端开发',
        '我是需求方/项目类型/1980梳理需求',
      ],
    },
    {
      type: 'category',
      label: '开发流程',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        '我是需求方/项目审核',
        '我是需求方/项目报价',
        '我是需求方/项目对接',
        '我是需求方/项目开发',
        '我是需求方/项目结提',
      ],
    },

    '我是需求方/权责纠纷',
    '我是需求方/常见问题',
  ],
  'developer': [
    {
      type: 'category',
      label: '远程工作',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        '我是开发者/开发工作/简介',
        '我是开发者/开发工作/签约开发者手册',
      ],
    },
    {
      type: 'category',
      label: '资源下载',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        '我是开发者/开发工作/简介',
      ],
    },
    {
      type: 'category',
      label: '客栈学院',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        '我是开发者/开发工作/简介',
      ],
    },
    '我是开发者/常见问题',
  ],
  'rules': [
    '规则协议/黑名单',
    {
      type: 'category',
      label: '协议',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        '规则协议/协议/用户协议',
        '规则协议/协议/会员协议',
        '规则协议/协议/账户注销协议',
        '规则协议/协议/程序员客栈工作规则',
        '规则协议/协议/隐私协议',
      ],
    },

  ],
};

module.exports = sidebars;
